
// This file has been generated by the GUI designer. Do not modify.
namespace LiteStatus
{
	public partial class MainWindow
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.VBox vbox3;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Label label7;
		private global::Gtk.Entry apiEntry;
		private global::Gtk.HBox hbox5;
		private global::Gtk.Label label8;
		private global::Gtk.Entry idEntry;
		private global::Gtk.Button timerBtn;
		private global::Gtk.Expander expander1;
		private global::Gtk.VBox vbox2;
		private global::Gtk.HBox balanceConfirmedhbox;
		private global::Gtk.Label label1;
		private global::Gtk.Label confirmedLabel;
		private global::Gtk.Label confirmedDiffLabel;
		private global::Gtk.HBox balanceUnconfirmedhbox;
		private global::Gtk.Label label3;
		private global::Gtk.Label unconfirmedLabel;
		private global::Gtk.HBox balanceOrphanedhbox;
		private global::Gtk.Label label4;
		private global::Gtk.Label orphanedLabel;
		private global::Gtk.Label GtkLabel1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LiteStatus.MainWindow
			this.Name = "LiteStatus.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child LiteStatus.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Api key:");
			this.hbox4.Add (this.label7);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label7]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.apiEntry = new global::Gtk.Entry ();
			this.apiEntry.CanFocus = true;
			this.apiEntry.Name = "apiEntry";
			this.apiEntry.IsEditable = true;
			this.apiEntry.InvisibleChar = '●';
			this.hbox4.Add (this.apiEntry);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.apiEntry]));
			w2.Position = 1;
			this.vbox3.Add (this.hbox4);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox4]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("ID:");
			this.hbox5.Add (this.label8);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label8]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.idEntry = new global::Gtk.Entry ();
			this.idEntry.CanFocus = true;
			this.idEntry.Name = "idEntry";
			this.idEntry.IsEditable = true;
			this.idEntry.InvisibleChar = '●';
			this.hbox5.Add (this.idEntry);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.idEntry]));
			w5.Position = 1;
			this.vbox3.Add (this.hbox5);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox5]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.timerBtn = new global::Gtk.Button ();
			this.timerBtn.CanFocus = true;
			this.timerBtn.Name = "timerBtn";
			this.timerBtn.UseUnderline = true;
			this.timerBtn.Label = global::Mono.Unix.Catalog.GetString ("Start");
			this.vbox3.Add (this.timerBtn);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.timerBtn]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox3]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.expander1 = new global::Gtk.Expander (null);
			this.expander1.CanFocus = true;
			this.expander1.Name = "expander1";
			this.expander1.Expanded = true;
			// Container child expander1.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.balanceConfirmedhbox = new global::Gtk.HBox ();
			this.balanceConfirmedhbox.Name = "balanceConfirmedhbox";
			this.balanceConfirmedhbox.Spacing = 6;
			// Container child balanceConfirmedhbox.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Confirmed:");
			this.balanceConfirmedhbox.Add (this.label1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.balanceConfirmedhbox [this.label1]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child balanceConfirmedhbox.Gtk.Box+BoxChild
			this.confirmedLabel = new global::Gtk.Label ();
			this.confirmedLabel.Name = "confirmedLabel";
			this.confirmedLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
			this.balanceConfirmedhbox.Add (this.confirmedLabel);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.balanceConfirmedhbox [this.confirmedLabel]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child balanceConfirmedhbox.Gtk.Box+BoxChild
			this.confirmedDiffLabel = new global::Gtk.Label ();
			this.confirmedDiffLabel.Name = "confirmedDiffLabel";
			this.confirmedDiffLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
			this.balanceConfirmedhbox.Add (this.confirmedDiffLabel);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.balanceConfirmedhbox [this.confirmedDiffLabel]));
			w11.PackType = ((global::Gtk.PackType)(1));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox2.Add (this.balanceConfirmedhbox);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.balanceConfirmedhbox]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.balanceUnconfirmedhbox = new global::Gtk.HBox ();
			this.balanceUnconfirmedhbox.Name = "balanceUnconfirmedhbox";
			this.balanceUnconfirmedhbox.Spacing = 6;
			// Container child balanceUnconfirmedhbox.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Unconfirmed:");
			this.balanceUnconfirmedhbox.Add (this.label3);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.balanceUnconfirmedhbox [this.label3]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child balanceUnconfirmedhbox.Gtk.Box+BoxChild
			this.unconfirmedLabel = new global::Gtk.Label ();
			this.unconfirmedLabel.Name = "unconfirmedLabel";
			this.unconfirmedLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
			this.balanceUnconfirmedhbox.Add (this.unconfirmedLabel);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.balanceUnconfirmedhbox [this.unconfirmedLabel]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			this.vbox2.Add (this.balanceUnconfirmedhbox);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.balanceUnconfirmedhbox]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.balanceOrphanedhbox = new global::Gtk.HBox ();
			this.balanceOrphanedhbox.Name = "balanceOrphanedhbox";
			this.balanceOrphanedhbox.Spacing = 6;
			// Container child balanceOrphanedhbox.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Orphaned:");
			this.balanceOrphanedhbox.Add (this.label4);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.balanceOrphanedhbox [this.label4]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child balanceOrphanedhbox.Gtk.Box+BoxChild
			this.orphanedLabel = new global::Gtk.Label ();
			this.orphanedLabel.Name = "orphanedLabel";
			this.orphanedLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
			this.balanceOrphanedhbox.Add (this.orphanedLabel);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.balanceOrphanedhbox [this.orphanedLabel]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			this.vbox2.Add (this.balanceOrphanedhbox);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.balanceOrphanedhbox]));
			w18.Position = 2;
			w18.Expand = false;
			w18.Fill = false;
			this.expander1.Add (this.vbox2);
			this.GtkLabel1 = new global::Gtk.Label ();
			this.GtkLabel1.Name = "GtkLabel1";
			this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("Balance");
			this.GtkLabel1.UseUnderline = true;
			this.expander1.LabelWidget = this.GtkLabel1;
			this.vbox1.Add (this.expander1);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.expander1]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.timerBtn.Clicked += new global::System.EventHandler (this.OnFetchBtnClicked);
		}
	}
}
